--------------------------------------------------------------------------------------------------------------
-- Items
--------------------------------------------------------------------------------------------------------------
require(xmx_prototypes_items_path .. "white-tile")
require(xmx_prototypes_items_path .. "assembling-machines")
require(xmx_prototypes_items_path .. "beacon")
require(xmx_prototypes_items_path .. "centrifuges")
require(xmx_prototypes_items_path .. "electric-poles")
require(xmx_prototypes_items_path .. "energy-productions")
require(xmx_prototypes_items_path .. "furnaces")
require(xmx_prototypes_items_path .. "inserter")
require(xmx_prototypes_items_path .. "item-groups")
require(xmx_prototypes_items_path .. "lamp")
require(xmx_prototypes_items_path .. "loader")
require(xmx_prototypes_items_path .. "mining-drills")
require(xmx_prototypes_items_path .. "oil-processing")
require(xmx_prototypes_items_path .. "pipes")
require(xmx_prototypes_items_path .. "pumps")
require(xmx_prototypes_items_path .. "radar")
require(xmx_prototypes_items_path .. "roboport")
require(xmx_prototypes_items_path .. "robots-flying")
require(xmx_prototypes_items_path .. "rocket-silo")
require(xmx_prototypes_items_path .. "storage-tank")
--require(xmx_prototypes_items_path .. "sink")
require(xmx_prototypes_items_path .. "trains")
require(xmx_prototypes_items_path .. "transport-belts")
require(xmx_prototypes_items_path .. "vehicles")
require(xmx_prototypes_items_path .. "waterfill")
--------------------------------------------------------------------------------------------------------------
-- Vanilla-Changes
--------------------------------------------------------------------------------------------------------------
require(xmx_prototypes_items_path .. "vanilla-changes/assembling-machines")
require(xmx_prototypes_items_path .. "vanilla-changes/beacon")
require(xmx_prototypes_items_path .. "vanilla-changes/chests")
require(xmx_prototypes_items_path .. "vanilla-changes/electric-poles")
require(xmx_prototypes_items_path .. "vanilla-changes/energy-productions")
require(xmx_prototypes_items_path .. "vanilla-changes/item-groups")
require(xmx_prototypes_items_path .. "vanilla-changes/landfill")
require(xmx_prototypes_items_path .. "vanilla-changes/pipes")
require(xmx_prototypes_items_path .. "vanilla-changes/trains")
require(xmx_prototypes_items_path .. "vanilla-changes/transport-belts")
require(xmx_prototypes_items_path .. "vanilla-changes/vehicles")