data.raw.item["transport-belt"].subgroup = "transport-belt"
data.raw.item["transport-belt"].order = "a[transport-belt]-b[xmx-mk2-transport-belt]"
data.raw.item["fast-transport-belt"].subgroup = "transport-belt"
data.raw.item["fast-transport-belt"].order = "a[transport-belt]-c[xmx-mk3-transport-belt]"
data.raw.item["express-transport-belt"].subgroup = "transport-belt"
data.raw.item["express-transport-belt"].order = "a[transport-belt]-d[xmx-mk4-transport-belt]"

data.raw.item["underground-belt"].subgroup = "underground-belt"
data.raw.item["underground-belt"].order = "b[underground-belt]-b[xmx-mk2-underground-belt]"
data.raw.item["fast-underground-belt"].subgroup = "underground-belt"
data.raw.item["fast-underground-belt"].order = "b[underground-belt]-c[xmx-mk3-underground-belt]"
data.raw.item["express-underground-belt"].subgroup = "underground-belt"
data.raw.item["express-underground-belt"].order = "b[underground-belt]-d[xmx-mk4-underground-belt]"

data.raw.item["splitter"].subgroup = "splitter"
data.raw.item["splitter"].order = "c[splitter]-b[xmx-mk2-splitter]"
data.raw.item["fast-splitter"].subgroup = "splitter"
data.raw.item["fast-splitter"].order = "c[splitter]-c[xmx-mk3-splitter]"
data.raw.item["express-splitter"].subgroup = "splitter"
data.raw.item["express-splitter"].order = "c[splitter]-d[xmx-mk4-splitter]"