--------------------------------------------------------------------------------------------------------------
-- Entities
--------------------------------------------------------------------------------------------------------------
require(xmx_prototypes_entities_path .. "white-tile")
-----------
-- Vanilla Changes
require(xmx_prototypes_entities_path .. "vanilla-changes/assembling-machines")
require(xmx_prototypes_entities_path .. "vanilla-changes/beacon")
require(xmx_prototypes_entities_path .. "vanilla-changes/centrifuges")
require(xmx_prototypes_entities_path .. "vanilla-changes/concrete")
require(xmx_prototypes_entities_path .. "vanilla-changes/electric-pole")
require(xmx_prototypes_entities_path .. "vanilla-changes/energy-productions")
require(xmx_prototypes_entities_path .. "vanilla-changes/furnaces")
require(xmx_prototypes_entities_path .. "vanilla-changes/inserter")
require(xmx_prototypes_entities_path .. "vanilla-changes/lamp")
require(xmx_prototypes_entities_path .. "vanilla-changes/mining-drills")
require(xmx_prototypes_entities_path .. "vanilla-changes/oil-processing")
require(xmx_prototypes_entities_path .. "vanilla-changes/pipes")
require(xmx_prototypes_entities_path .. "vanilla-changes/pumps")
require(xmx_prototypes_entities_path .. "vanilla-changes/radar")
require(xmx_prototypes_entities_path .. "vanilla-changes/roboport")
require(xmx_prototypes_entities_path .. "vanilla-changes/storage-tank")
require(xmx_prototypes_entities_path .. "vanilla-changes/transport-belts/transport-belts")
require(xmx_prototypes_entities_path .. "vanilla-changes/transport-belts/underground-belts")
require(xmx_prototypes_entities_path .. "vanilla-changes/transport-belts/splitter")
-----------
-- Remnants
require(xmx_prototypes_entities_path .. "beacon/beacon-remnants")
require(xmx_prototypes_entities_path .. "centrifuges/centrifuges-remnants")
require(xmx_prototypes_entities_path .. "electric-pole/electric-pole-remnants")
require(xmx_prototypes_entities_path .. "energy-productions/energy-productions-remnants")
require(xmx_prototypes_entities_path .. "furnaces/furnaces-remnants")
require(xmx_prototypes_entities_path .. "inserter/inserter-remnants")
require(xmx_prototypes_entities_path .. "lamp/lamp-remnants")
require(xmx_prototypes_entities_path .. "mining-drills/mining-drills-remnants")
require(xmx_prototypes_entities_path .. "oil-processing/oil-processing-remnants")
require(xmx_prototypes_entities_path .. "pipes/pipes-remnants")
require(xmx_prototypes_entities_path .. "pumps/pumps-remnants")
require(xmx_prototypes_entities_path .. "transport-belts/remnant/transport-belt-remnant")
require(xmx_prototypes_entities_path .. "transport-belts/remnant/underground-belt-remnant")
require(xmx_prototypes_entities_path .. "transport-belts/remnant/splitter-remnant")
require(xmx_prototypes_entities_path .. "radar/radar-remnants")
require(xmx_prototypes_entities_path .. "rocket-silo/rocket-silo-remnants")
require(xmx_prototypes_entities_path .. "storage-tank/storage-tank-remnants")
require(xmx_prototypes_entities_path .. "trains/trains-remnants")
require(xmx_prototypes_entities_path .. "vehicles/vehicles-remnants")
--require(xmx_prototypes_entities_path .. "sink/sink-remnants")
-----------
-- Transport Belts
require(xmx_prototypes_entities_path .. "transport-belts/transport-belts")
require(xmx_prototypes_entities_path .. "transport-belts/underground-belts")
require(xmx_prototypes_entities_path .. "transport-belts/splitter")
require(xmx_prototypes_entities_path .. "loader")
-----------
-- 
require(xmx_prototypes_entities_path .. "assembling-machines/assembling-machines")
require(xmx_prototypes_entities_path .. "beacon/beacon")
require(xmx_prototypes_entities_path .. "centrifuges/centrifuges")
require(xmx_prototypes_entities_path .. "electric-pole/electric-pole")
require(xmx_prototypes_entities_path .. "energy-productions/energy-productions")
require(xmx_prototypes_entities_path .. "furnaces/furnaces")
require(xmx_prototypes_entities_path .. "inserter/inserter")
require(xmx_prototypes_entities_path .. "lamp/lamp")
require(xmx_prototypes_entities_path .. "mining-drills/mining-drills")
require(xmx_prototypes_entities_path .. "oil-processing/oil-processing")
require(xmx_prototypes_entities_path .. "pipes/pipes")
require(xmx_prototypes_entities_path .. "pumps/pumps")
require(xmx_prototypes_entities_path .. "radar/radar")
require(xmx_prototypes_entities_path .. "rocket-silo/rocket-silo")
require(xmx_prototypes_entities_path .. "roboport")
require(xmx_prototypes_entities_path .. "robots/robots-flying")
require(xmx_prototypes_entities_path .. "storage-tank/storage-tank")
require(xmx_prototypes_entities_path .. "trains/trains")
require(xmx_prototypes_entities_path .. "vehicles/vehicles")
--require(xmx_prototypes_entities_path .. "sink/sink")
-----------
-- Graphics
require(xmx_prototypes_entities_path .. "inserter/inserter-graphics")